version: '3.8'

services:
  0lpidnamespace:
    image: alpine:latest
    container_name: "0l-pid-namespace"
    command: sh -c "tail -f /dev/null"
    user: 9999:9999
    restart: on-failure
    env_file:
      - "../.env"
